.TH JULIET "1" "Oct 2018" "juliet 0.2-alpha2" "User Commands"
.SH NAME
juliet \- The lightweight static website generator
.SH DESCRIPTION
.PP
Juliet is a powerful, yet experimental static websites generator written in Python. It is designed to be as lightweight and understandable as possible.
.SH USAGE
juliet [\-h] [\-\-debug] [\-\-version] {build,init,new} ...
.SS "positional arguments:"
.TP
{build,init,new}
sub\-command to be executed
.TP
build
Build static site from local directory to the directory
specified in config.yml
.TP
init
Initialize a new, clean website in current directory.
.TP
new
Initialize a fresh, new article file.
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit. When called with positional arguments, it provides more specific information about these.
.HP
\fB\-\-debug\fR, \fB\-d\fR
.TP
\fB\-\-version\fR, \fB\-v\fR
show program's version number and exit
.SH COPYRIGHT
This manual page is Copyright © 2018 Hugo Lefeuvre <hle@owl.eu.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 or any later version published by the Free Software Foundation.
